Rising Temperature

https://leetcode.com/problems/rising-temperature/

Solved on 2026-06-22.

Given a table `Weather` with the following columns:

- `id`: the ID of the weather
- `recordDate`: the date of the weather
- `temperature`: the temperature of the weather

Write a solution to find all dates' Id with higher temperatures compared to its previous dates (yesterday).

Return the result table in any order.

## Solution

```{sql}
SELECT
    w2.id
FROM
    Weather AS w1
JOIN
    Weather As w2 ON w2.recordDate = (w1.recordDate + 1)
    AND w2.temperature > w1.temperature
ORDER BY
    w2.id;
```

## Explanation

We use self-join to find the dates with higher temperatures compared to its previous dates. We join the `Weather` table with itself on the `recordDate` column, with the condition that the `recordDate` of the second row is the next day of the first row. We then filter for rows where the `temperature` of the second row (current day) is greater than the `temperature` of the first row (previous day) and return the id of the current day. We then order the result by `id` (unnecessary, but nice to have) and return the `id` column.