Queries Quality and Percentage

https://leetcode.com/problems/queries-quality-and-percentage/

Solved 2026-10-04

We define query quality as:

The average of the ratio between query rating and its position.

We also define poor query percentage as:

The percentage of all queries with rating less than 3.

Write a solution to find each query_name, the quality and poor_query_percentage.

Both quality and poor_query_percentage should be rounded to 2 decimal places.

Return the result table in any order.

## Solution

```sql
-- Write your PostgreSQL query statement below
SELECT
    query_name,
    ROUND(AVG(rating::numeric/position), 2) AS quality,
    ROUND(AVG((rating<3)::int) * 100.0, 2) AS poor_query_percentage
FROM
    Queries
GROUP BY
    query_name
;
```

## Explanation

We first group by query_name to derive the quality and poor query percentage for each query_name separately. quality is simply the average of the ratio between rating and position (rating is casted as numeric to follow the AVG function requirement when providing an integer to indicate decimal places). poor_query_percentage is calculated by identifying the rows where rating is less than 3, translating it to 1's and 0's, then taking the average of the 1's and 0's (and multiplying by 100 to get the percentage).