User Activity for the Past 30 Days I

https://leetcode.com/problems/user-activity-for-the-past-30-days-i/description/

Solved 2026-10-03

Write a solution to find the daily active user count for a period of 30 days ending 2019-07-27 inclusively. A user was active on someday if they made at least one activity on that day.

Return the result table in any order.

The result format is in the following example.

Note: Any activity from ('open_session', 'end_session', 'scroll_down', 'send_message') will be considered valid activity for a user to be considered active on a day.

## Solution

```sql
-- Write your PostgreSQL query statement below
SELECT
    activity_date AS day,
    COUNT(DISTINCT user_id) AS active_users
FROM
    Activity
WHERE
    activity_date BETWEEN '2019-07-27'::date-29 AND '2019-07-27'::date
    AND activity_type IN ('open_session', 'end_session', 'scroll_down', 'send_message')
GROUP BY
    activity_date
;
```

## Explanation

We first filter from the Activity table only the desired dates and the desired activity types. For this filter result, we group by the activity date since we want to summarize this for each day. Then, for each day, we count the number of distinct users who were active on that day, as desired.