Average Selling Price

https://leetcode.com/problems/average-selling-price/description/

Solved 2026-10-04

Write a solution to find the average selling price for each product. average_price should be rounded to 2 decimal places. If a product does not have any sold units, its average selling price is assumed to be 0.

Return the result table in any order.

## Solution

```sql
-- Write your PostgreSQL query statement below
SELECT
    p.product_id,
    COALESCE(
        ROUND((SUM(p.price * us.units))::numeric/ (SUM(us.units)), 2),
        0
    ) AS average_price
FROM
    Prices AS p
    LEFT OUTER JOIN UnitsSold AS us
        ON p.product_id = us.product_id
        AND us.purchase_date BETWEEN p.start_date and p.end_date
GROUP BY
    p.product_id
;
```

## Explanation

We first performa left outer join of Prices with UnitsSold on the conditions that the product_id matches and the purchase_date corresponds to the correct effective price date range. If there are no matching rows (indicating no purchases made), these will show up as NULL later on. We then group by the product_id. We calculate the unit-weighted-average price if the row has non-NULL values when joined with UnitsSold. If the row contains NULL values from UnitsSold, we return 0 as the average price (which is done via COALESCE). This gives us what we need.